Repository bitzquad/bitzquad.com-2.0, pull requests merged in 2022-10, with the labels that each got.

#47 fix: image top padding 🐛
  public/assets/img/squad/ashene.webp
  public/assets/img/squad/harsha.webp
  public/assets/img/squad/tharuka.webp
Labels: bug

#50 blog title extract ok
  package-lock.json
  pages/blog/[slug].js
  pages/blog/index.js
  posts/coding-best-practices.md
  posts/ed-trends-waiting-to-say-hello-in-2023.md
Labels: enhancement

#52 Blog Section Navigation.
  pages/blog/[slug].js
Labels: enhancement

#53 fix link extract issue
  pages/blog/[slug].js
Labels: bug

#55 Fix MD sanitation issue
  package-lock.json
  package.json
  pages/blog/[slug].js
Labels: bug

#54 Production Push : Feature Blog ✨
  components/blog/Code.js
  components/defaults/Footer.js
  components/defaults/Navbar.js
  components/defaults/SideMenu.js
  components/index.js
  components/layouts/LayoutMain.js
  components/layouts/LayoutSubPages.js
  package-lock.json
  package.json
  pages/blog/[slug].js
  pages/blog/index.js
  posts/ed-trends-waiting-to-say-hello-in-2023.md
  public/assets/img/blog/ed-trends-cover.webp
  public/assets/img/blog/ed-trends-main.webp
  styles/_pages.scss
  styles/base/_base.scss
  styles/pages/_blog-page.scss
  tailwind.config.js
Labels: enhancement

#56 fix meta image urls
  .env
  components/layouts/LayoutMain.js
  pages/404.js
  pages/about/index.js
  pages/blog/[slug].js
  pages/blog/index.js
  pages/comingsoon.js
  pages/contact/index.js
  pages/index.js
  pages/projects/index.js
  pages/squad/[id].js
  pages/squad/index.js
  posts/ed-trends-waiting-to-say-hello-in-2023.md
Labels: bug

#67 Blog views
  .eslintrc.json
  credentials.json
  next.config.js
  package-lock.json
  package.json
  pages/api/analytics/index.js
  pages/blog/[slug].js
  public/robots.txt
  public/sitemap.xml
Labels: bug, enhancement

#70 fix: url value bug
  posts/how-going-serverless-will-help-your-business.md
Labels: enhancement
