Repository bitzquad/bitzquad.com-2.0, pull requests merged in 2022-08, with the labels that each got.

#17 Feature squad page
  assets/images/squad/role/founder-bg-text.svg
  constants/images.js
  constants/members.js
  pages/squad/[id].js
  pages/squad/index.js
Labels: enhancement

#20 fix: squad page alignments 🐛
  pages/squad/index.js
  styles/_tailwind.scss
  tailwind.config.js
Labels: bug

#21 fix B20-30 Collaborate section issue
  components/elements/Button.js
  components/home/Collaborate.js
  package-lock.json
  package.json
  styles/pages/_home-page.scss
Labels: bug

#19 Admin dashboard
  .env
  components/index.js
  components/layouts/LayoutAdmin.js
  constants/adminmenu.js
  constants/hooks/getMenu.js
  constants/schemas/Contact.js
  constants/schemas/News.js
  constants/schemas/Newsletter.js
  constants/schemas/contact.js
  constants/schemas/newsletter.js
  constants/schemas/user.js
  constants/stores/userStore.js
  middleware/queryparser.js
  middleware/request.js
  package-lock.json
  package.json
  pages/admin/blog/add.js
  pages/admin/blog/all.js
  pages/admin/blog/index.js
  pages/admin/blog/overview.js
  pages/admin/dashboard/index.js
  pages/admin/dashboard/overview.js
  pages/admin/index.js
  pages/admin/news/add.js
  pages/admin/news/all.js
  pages/admin/news/index.js
  pages/admin/news/overview.js
  pages/admin/other/contact.js
  pages/admin/other/index.js
  pages/admin/settings/index.js
  pages/admin/user/add.js
  pages/admin/user/all.js
  pages/admin/user/index.js
  pages/admin/user/overview.js
  pages/api/Contact/index.js
  pages/api/News/index.js
  pages/api/auth/[fname].js
  pages/api/contact/index.js
  pages/api/news/index.js
  pages/api/newsletter/[fname].js
  pages/api/user/index.js
  tailwind.config.js
Labels: enhancement

#23 fix dev build error
  tailwind.config.js
Labels: bug

#24 footer ok
  components/defaults/Footer.js
  tailwind.config.js
Labels: enhancement

#22 fix: sidemenu responsive and overlay 🐛
  components/defaults/Navbar.js
  pages/index.js
  styles/components/_sidemenu.scss
Labels: bug

#25 Feature project page ✨
  components/defaults/Footer.js
  constants/projects.js
  pages/projects/[id].js
  pages/projects/index.js
  styles/components/_cursor.scss
Labels: enhancement

#28 fix: page scrolling with sidemenu open 🐛
  components/defaults/Navbar.js
Labels: bug

#27 about section
  assets/images/about/1.svg
  assets/images/about/2.svg
  assets/images/about/3.svg
  constants/about.js
  constants/images.js
  pages/about/index.js
Labels: enhancement

#32 feat: services section
  assets/images/services-exp.png
  components/home/Landing.js
  components/home/Services.js
  constants/images.js
  pages/index.js
  styles/_tailwind.scss
  styles/base/_base.scss
  styles/pages/_home-page.scss
Labels: enhancement

#31 feature contact section
  assets/images/contact/bg-sm.svg
  assets/images/contact/bg.svg
  constants/images.js
  pages/contact/index.js
Labels: enhancement

#33 feature - project section
  assets/images/proj-sec-bg.png
  components/home/ProjectSection.js
  components/index.js
  constants/images.js
  pages/index.js
  styles/pages/_home-page.scss
Labels: enhancement

#34 Add text content
  .eslintrc.json
  components/defaults/Footer.js
  components/defaults/Navbar.js
  components/defaults/SideMenu.js
  components/home/Collaborate.js
  components/home/Landing.js
  components/home/ProjectSection.js
  components/home/Services.js
  constants/about.js
  pages/about/index.js
  pages/contact/index.js
  pages/squad/index.js
  styles/pages/_home-page.scss
Labels: enhancement

#35 Finalize
  .env
  .eslintrc.json
  assets/images/services-exp.png
  components/defaults/Footer.js
  components/defaults/Navbar.js
  components/defaults/SideMenu.js
  components/elements/Button.js
  components/home/Collaborate.js
  components/home/Landing.js
  components/home/ProjectSection.js
  components/home/Services.js
  constants/members.js
  constants/projects.js
  constants/schemas/contact.js
  pages/404.js
  pages/_app.js
  pages/about/index.js
  pages/api/contact/index.js
  pages/comingsoon.js
  pages/contact/index.js
  pages/projects/index.js
  pages/squad/[id].js
  pages/squad/index.js
  public/assets/img/projects/deinclusive-1.png
  public/assets/img/squad/akash.png
  public/assets/img/squad/ashene.png
  public/assets/img/squad/harindu.png
  public/assets/img/squad/harsha.png
  public/assets/img/squad/hasindu.png
  public/assets/img/squad/isuru.png
  public/assets/img/squad/kesara.png
  public/assets/img/squad/nuwantha.png
  public/assets/img/squad/ridmi.png
  public/assets/img/squad/sandun.png
  public/assets/img/squad/sanjana.png
  public/assets/img/squad/tharuka.png
  styles/_tailwind.scss
  styles/components/_header.scss
  styles/components/_sidemenu.scss
  styles/pages/_home-page.scss
Labels: bug, enhancement
